### ISSUE TITLE
can it copy file to usb storage?

### ISSUE THREAD

**Issue by z-huabao** [jacklinquan/usbserial4a#1]
Hello, I make a kivy app, and want to copy a file from android  to a usb storage by `shutil.copy('/sdcard/***', '/storage/***/myfolder/')`, 
but get error: `permissson denied`, even I have got the `WRITE_EXTERNAL_STORAGE` permission.

So, can I use you project to do this? how to do it?

**Comment by jacklinquan** [comment]
This package includes the drivers of USB serial devices for Android(E.g. USB to UART). It has nothing to do with USB storage nor any external storage. It doesn't need WRITE_EXTERNAL_STORAGE permission at all.

**Comment by z-huabao** [comment]
ok, thanks for your ans.
