### ISSUE TITLE
Usb serial 4A for chaquopy ?

### ISSUE THREAD

**Issue by arwysyah** [jacklinquan/usbserial4a#12]
Hi @jacklinquan ,  i have a question, is it possible to implement this module usbserial4 with chaquopy ? Without UI from Kivy ?
Thank you 🙏🏻

**Comment by jacklinquan** [comment]
Hi @arwysyah ,

I never played with `chaquopy` yet. `usbserial4a` depends on `usb4a` which in turn depends on `pyjnius` from `kivy`.

With the help of `pyjnius`, `usb4a` introduces several java class into python environment:
```python
from jnius import autoclass

PythonActivity = autoclass('org.kivy.android.PythonActivity')
PythonService = autoclass('org.kivy.android.PythonService')
Context = autoclass('android.content.Context')
Intent = autoclass('android.content.Intent')
PendingIntent = autoclass('android.app.PendingIntent')

UsbConstants = autoclass('android.hardware.usb.UsbConstants')
UsbRequest = autoclass('android.hardware.usb.UsbRequest')

ByteBuffer = autoclass('java.nio.ByteBuffer')
```

If `chaquopy` can offer the equivalent classes as above, it would be possible.

**Comment by arwys** [comment]
interesting, i am not python guy, but i think it won’t wrong to try it 😁 ,thank you  so much@jacklinquan

**Comment by adabru** [comment]
@arwys maybe you can use Buildozer directly to avoid the UI part. If you want to use chaquopy for usb-serial on android you might look at https://github.com/pyserial/pyserial/pull/780 .
