### ISSUE TITLE
Send Integer From Android to Arduino Serially

### ISSUE THREAD

**Issue by gepetto82** [jacklinquan/usbserial4a#13]
How can I use the 

serial_port.write(b'Hello world!')

Command given at the end of the example.py document to send an integer from android device to arduino?

**Comment by jacklinquan** [comment]
Serial communication sends all kinds of data in sequence of bytes.
The sending and receiving devices must agree on how these bytes are packed and unpacked.
In your code, you can do this by using `struct.pack` and `struct.unpack`.

**Comment by jacklinquan** [comment]
Since this is not a real issue, I will close it in 24 hours.
