### ISSUE TITLE
stm32 device no response

### ISSUE THREAD

**Issue by premanandaembed** [jacklinquan/usbserial4a#17]
read and write totally not worked for me apart from device detection.

**Comment by jacklinquan** [comment]
@premanandaembed 
Please give more info:
1. What USB-serial driver are you using?
2. How you test it?
3. Your code.
4. What result did you get?

**Comment by premanandaembed** [comment]
thank you so much for reply. I will post

**Comment by premanandaembed** [comment]
I tried using Pydroid3 App and installed usbserial4a package and your code example/usbserial4a_ui_example.py  and it is not getting any response?(see images from bottom to top)

![Screenshot3_Pydroid 3](https://github.com/jacklinquan/usbserial4a/assets/64586165/8098a2eb-4ffe-4695-8b7d-686f4096ef69)
![Screenshot2_Pydroid 3](https://github.com/jacklinquan/usbserial4a/assets/64586165/71312023-180f-4fa3-82c0-84f601b357bb)
![Screenshot1_Pydroid 3](https://github.com/jacklinquan/usbserial4a/assets/64586165/dc9362e4-9026-4224-8f67-9ec88b646d4b)

**Comment by jacklinquan** [comment]
@premanandaembed 
Could you tell which USB-serial IC is used in the hardware?
For example: FTDI, CP210x, CH34x, etc.

**Comment by premanandaembed** [comment]
which devices are not supported i want to know?

**Comment by jacklinquan** [comment]
@premanandaembed 

Implemented drivers are listed below:
FTDI serial driver - done and tested with FT230X.
CDC ACM serial driver - done and tested with MCP2200, BBC micro:bit V1(nRF51).
CP210x serial driver - done and tested with CP2102.
CH34x serial driver - done and tested with CH340.
PL2303 serial driver - done and tested with PL2303.

Devices other than these are not supported (or not tested).
