### ISSUE TITLE
Build Process Fails for example.py

### ISSUE THREAD

**Issue by ghost** [jacklinquan/usbserial4a#19]
The instructions say they are outdated. Are there updated ones? The build removes the /xml directory.

[WARNING]: ERROR: /workspace/.buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/myapp/gradlew failed!
No setup.py/pyproject.toml used, copying full private data into .apk.
Applying Java source code patches...
Applying patch: src/patches/SDLActivity.java.patch
Warning: failed to apply patch (exit code 1), assuming it is already applied:  src/patches/SDLActivity.java.patch

**Comment by jacklinquan** [comment]
@berrios1 
`example.py` has no UI. It can not be built into an app.
For app example, try `usbserial4a_ui_example.py`.
