### ISSUE TITLE
USB disconnection seems not properly handled

### ISSUE THREAD

**Issue by zh5j** [jacklinquan/usbserial4a#20]
**Hi, first of all, thanks for the amazing project, it's very easy to use and helped me a lot.** 

Now that I'm trying to integrate serial communications into my android Kivy app, I had a weird observation...

When the serial is initialized without timeout, unplugging the USB cable does not cause serial.readline() to raise an exception, unlike the behavior of pyserial in desktop Linux. 

If the serial port is initialized with a timeout, then readline() simply returns an empty bytes object, same as if the USB cable hasn't been disconnected and nothing has been received. 

Plugging the device back in does not trigger automatic reconnection of the serial port, as expected. But neither does it trigger a permission request dialog, which is weird... 

This is the error output by pyserial on desktop when USB gets disconnected during a readline() call: `device reports readiness to read but returned no data (device disconnected or multiple access on port?)`

No such errors existed in logcat output, and I believe I've catched all exceptions (see code below).

**So, question: how to detect disconnections of the USB serial device? And what considerations are needed when attempting to recover from a disconnection?**

Relevant info: 
Android version: 11
Serial device type: STM32 USB CDC ACM
Kivy version: 2.3.0
Python version: v3.11.5 (main, Oct 27 2024, 18:56:32) [Clang 14.0.6 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0

(the app is generated using pretty much the default config of buildozer except adding necessary components)

Snippet of code (which runs in separate thread to handle serial disconnections + print serial data) is attached below. Note: `log_append()` simply displays a text string at a designated area in my UI. 

```python
#-------------------------------------------------------------------------------------
# task for getting data from USB serial
def serial_recover_threadmain(self, *args):
    # task never ends
    while 1:
        # whenever something goes wrong with the serial port, consider it disconnected
        # the code should set serial_port to None
        if self.serial_port:
            try:
                msg = self.serial_port.readline()
                self.log_append(msg)
            except BaseException as e:
                self.log_append("USB read error: " , e)
                #self.loop.remove_reader(self.serial_port)
                self.serial_port = None
            continue

        # serial no working (yet?)
        # avoid blocking or flooding the log box
        time.sleep(3)

        # for android
        if platform == 'android':
            # this is copied from usbserial4a example
            # find all USB devices
            usb_device_list = usb.get_usb_device_list()
            # nothing connected?
            if not len(usb_device_list):
                self.log_append('No USB devices!')
                continue
            # is this our device?
            self.device_name_list = [device for device in usb_device_list if device.getProductName() == 'somedevice']
            if not len(self.device_name_list):
                # nope, not our device
                self.log_append('Unknown USB device!')
                continue
            if len(self.device_name_list) > 1:
                # yes, but more than one detected (unlikely!)
                self.log_append('Multiple devices detected!')
                continue
            # we have now located the USB device, try to open it
            device = self.device_name_list[0]
            # try to request permission
            if not usb.has_usb_permission(device):
                usb.request_usb_permission(device)
                continue
            try:
                self.serial_port = serial4a.get_serial_port(device.getDeviceName(), timeout=0.3)
            except BaseException as e:
                self.log_append('Failed to connect to USB: ' + str(e))
                self.serial_port = None
                continue

            self.log_append('Device connected!')
            # self.loop.add_reader(self.serial_port, self.serial_read_threadmain)

        # for desktop
        if platform == 'linux':
            try:
                # locate device by ID
                usb_device_list = ['/dev/serial/by-id/' + d for d in os.listdir('/dev/serial/by-id/') if d.startswith('usb-somedevice')]
            except FileNotFoundError:
                # nothing with ID is connected so Linux removes that folder
                self.log_append('No USB device!')
                continue
            if len(usb_device_list) == 0:
                # some device with other IDs are connected but nothing of interest
                self.log_append('Unknown USB device!')
                continue
            if len(usb_device_list) > 1:
                # more than one devices of interest, abort operations
                self.log_append('Multiple devices detected!')
                continue
            # Now we have located the only USB device of interest, try to open it
            try:
                self.serial_port = Serial(usb_device_list[0])
            except BaseException as e:
                # permission issues? other issues? print the issue & exit
                self.log_append('Failed to connect to USB: ' + str(e))
                self.serial_port = None
                continue

            self.log_append('Device connected!')
            # self.loop.add_reader(self.serial_port, self.serial_read_threadmain)

```

The hardware dongle consists of an STM32 MCU dev kit with type-C connector. Both CC lines are pulled down with 5.1K as per USB spec, and connection is made using a C-C cable. USB device name has been customized to help identifying, but not the VID and PID values.

Example dmesg output on linux desktop when device is connected:
```
[30322.573388] usb 1-7: new full-speed USB device number 13 using xhci_hcd
[30322.701114] usb 1-7: New USB device found, idVendor=0483, idProduct=5740, bcdDevice= 2.00
[30322.701118] usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[30322.701119] usb 1-7: Product: somedevice
[30322.701120] usb 1-7: Manufacturer: somedevice
[30322.701121] usb 1-7: SerialNumber: xxxxxxxxxxxx
[30322.704068] cdc_acm 1-7:1.0: ttyACM0: USB ACM device
```

**Any help would be much appreciated!**

**Comment by zh5j** [comment]
For those of you facing similar issue, I started a separate thread in the app which periodically writes an empty line (b'\r\n') to the serial. My serial device discards empty lines, so this does not disrupt normal communication. The app detects an error when trying to write to a disconnected serial port, and returns to a disconnected state.

**Comment by jacklinquan** [comment]
> For those of you facing similar issue, I started a separate thread in the app which periodically writes an empty line (b'\r\n') to the serial. My serial device discards empty lines, so this does not disrupt normal communication. The app detects an error when trying to write to a disconnected serial port, and returns to a disconnected state.

Hi @wuzhongjie1997 
With this python package, you have to handle disconnection in your own code.
A way to detect disconnection is to call `usb.get_usb_device_list()`. When this list is empty, you can say the device is unplugged. In case the device does exist in `usb.get_usb_device_list()`, further check `usb.has_usb_permission(device)`. If it return `False`, the device could have been unplugged and plugged again.
