### ISSUE TITLE
Is it possible to turn on/off pins with ftdiserial4a.py

### ISSUE THREAD

**Issue by Larrxi** [jacklinquan/usbserial4a#7]
Hello I am totally new with these things and wonder:

Can ftdiserial4a be used to turn on/off pins? Can it be modified to have that functionality?

I have a CJMCU FT232H and I want to plug it to my android and want to control its pins.

**Comment by jacklinquan** [comment]
> Hello I am totally new with these things and wonder:
> 
> Can ftdiserial4a be used to turn on/off pins? Can it be modified to have that functionality?
> 
> I have a CJMCU FT232H and I want to plug it to my android and want to control its pins.

Hi @Larrxi 
This package only focuses on USB serial communication.
Other functions like GPIO, I2C and SPI of FTDI chips are not supported.
It is possible to implement GPIO functions by modifying ftdiserial4a.py, but that requires some knowledge on specific FTDI chips.
