### ISSUE TITLE
Read value from serial monitor

### ISSUE THREAD

**Issue by ghost** [jacklinquan/usbserial4a#8]
Hi. How can I read some value sent from the arduino to the device?

**Comment by jacklinquan** [comment]
Please refer to [the UI example](https://github.com/jacklinquan/usbserial4a/blob/master/example/usbserial4a_ui_example.py) for reading data.

**Comment by gustavo-a7** [comment]
Ok, thanks 😊

Em qui, 19 de ago de 2021 7:21 AM, Quan Lin ***@***.***>
escreveu:
